<!DOCTYPE html>
<html>
<head>
    <!-- Standard Meta -->
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">

    <!-- Site Properities -->
    <title>Bilextra</title>
    <link rel="stylesheet" type="text/css" href="<?= $assetPath ?>css/semantic.min.css">
    <link rel="stylesheet" type="text/css" href="<?= $assetPath ?>css/main.css">

    <script src="<?= $assetPath ?>js/jquery.min.js"></script>
    <script src="<?= $assetPath ?>js/semantic.min.js"></script>
    <script src="<?= $assetPath ?>js/main.js"></script>
</head>
<body>
<section class="main bilextra">
    <div class="ui grid container">
        <div class="sixteen wide column">
            <div class="ui hidden divider"></div>
            <div class="ui red center aligned raised segment">
                <strong>WARNING:</strong> Due to increased demand for our free trial we cannot guarantee supply.<br>As of <strong><?= date('Y-m-d') ?></strong> we currently have the product <strong>IN STOCK</strong> and are ready to ship within 24 hours of purchase.
            </div>
        </div>
        <div class="ten wide center aligned column">
            <h1 class="product-name bilextra">Bilextra</h1>
            <span class="product-tag bilextra">Get rid of all<br>your recurring problems</span>
            <img src="<?= $assetPath ?>images/bottles_bil.svg" class="bottles">
            <img src="<?= $assetPath ?>images/hurry_bil.svg" class="hurry">
        </div>
        <div class="six wide column">
            <div class="ui segments">
                <h3 class="ui inverted segment black center aligned header">
                    GET YOUR BOTTLE NOW!
                </h3>
                <div class="ui segment">
                    <?php if (isset($errors)): ?>
                        <div class="ui error message">
                            <strong>Please check the following errors:</strong>
                            <ul>
                                <?php foreach ($errors as $error): ?>
                                    <li><?= $error ?></li>
                                <?php endforeach ?>
                            </ul>
                        </div>
                    <?php endif ?>
                    <!-- Form -->
                    <form class="ui small form" method="post">
                        <button class="fluid ui right labeled icon blue huge button">
                            <i class="right arrow icon"></i>Buy Now
                        </button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</section>
<section class="why">
    <div class="ui three column internally celled grid container">
        <div class="column">
            <h3>Powerful Features</h3>
            <p>Gain control, reduce risk, and streamline management of your subscription business.</p>
        </div>
        <div class="column">
            <h3>Dispute Management</h3>
            <p>Automate the dispute process, from importing chargebacks to generating representation documentation, canceling subscriptions, and even preventing future chargebacks.</p>
        </div>
        <div class="column">
            <h3>Handling Billing Failure</h3>
            <p>We believe that through proper handling of billing failure, or dunning, you can increase your revenues and reduce your costs.</p>
        </div>
    </div>
</section>
</body>
</html>
