<!DOCTYPE html>
<html>
<head>
    <!-- Standard Meta -->
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">

    <!-- Site Properities -->
    <title>Bilextra</title>
    <link rel="stylesheet" type="text/css" href="<?= $assetPath ?>css/semantic.min.css">
    <link rel="stylesheet" type="text/css" href="<?= $assetPath ?>css/main.css">

    <script src="<?= $assetPath ?>js/jquery.min.js"></script>
    <script src="<?= $assetPath ?>js/semantic.min.js"></script>
    <script src="<?= $assetPath ?>js/main.js"></script>
</head>
<body>
<section class="main bilextra">
    <div class="ui grid container">
        <div class="sixteen wide column">
            <div class="ui hidden divider"></div>
            <div class="ui red center aligned raised segment">

            </div>
        </div>
        <div class="six wide column">
            <div class="ui segments">
                <div class="ui segment">
                    <!-- Form -->
                    <form class="ui small form" method="post">
                        <button class="fluid ui right labeled icon blue huge button">
                            <i class="right arrow icon"></i>Add extra $49
                        </button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</section>
<section class="why">
    <div class="ui three column internally celled grid container">
        <div class="column">
            <h3>Powerful Features</h3>
            <p>Gain control, reduce risk, and streamline management of your subscription business.</p>
        </div>
        <div class="column">
            <h3>Dispute Management</h3>
            <p>Automate the dispute process, from importing chargebacks to generating representation documentation, canceling subscriptions, and even preventing future chargebacks.</p>
        </div>
        <div class="column">
            <h3>Handling Billing Failure</h3>
            <p>We believe that through proper handling of billing failure, or dunning, you can increase your revenues and reduce your costs.</p>
        </div>
    </div>
</section>
</body>
</html>
